### PR TITLE
Variables support in CreateService

### PR DESCRIPTION
**Pull request by micwiel**
Hi, I'm trying implement variables support in CreateService. It can be useful when you want to use for example nrpe checks in terraform.

### CODE REVIEW

**Comment by lrsmith** [comment]
Taking a look and looking at the failed test

**Comment by lrsmith** [comment]
micwiel,  The test are passing but I would like to have some test around setting the variables and verify that they are being set. I'll look at adding some and if you could that would be good. Once there are a few test I think this will be good to merge in. Thanks Len

**Comment by micwiel** [comment]
I implemented test to check if setting variables is working. Could you tell me if is it ok now?

**Comment by lrsmith** [comment]
Thank you for the test. Give me a few days to review. Thanks again

**Comment by lrsmith** [comment]
Wanted to post that I will take a look in the next few days. Sorry for the delay.

**Pull request merged**
